### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by madhushreeray30** [ajmaradiaga/steampipe-plugin-btp#1]
Thanks @ajmaradiaga for this new plugin. Great work 🎉 !!

The basic structure looks good so far. While using the plugin, we did come up with a few suggestions based on our best practices:

`config/btp.spc`
  - We should have a single file named `btp.spc` under the `config` folder that will contain a basic connection for the plugin (see  [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc) for reference)
  - Could you please update the `btp.spc` file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
  - Can you mention which of these parameters are required and which are optional as done in the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
  - We should mention values for all the config arguments however commented out and the values should be in the format of the actual values (however incorrect)
  - We should also add details to set these parameters via the environment variable (if any)

`docs/tables/*`
  - We should have a folder called `docs` under which we will have a single file called `index.md` ([reference](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/docs/index.md)) and individual table docs for each table
  - The table docs should be named as eg > `btp_datacenter.md` (note: The table names should be singular)
  - Each table doc should have the following parts >
    - A heading in the format > `# Table: btp_datacenter`
    - A description of the table
    - A number of queries which will have the `title` followed by the query (Note: We do not include the query outputs in the docs)

`docs/index.md`
  - Needs to be added ([reference](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/docs/index.md))
  
`btp/*`
  - Please add the configuration for setting the config arguments via the environment variable
  - The table file names should be in singular and in snake_case for example : `table_btp_accounts_directories.go`
  - The table file name should be in sync with the table name in the code
  - It is better to print the type of error when we encounter any like `connection_error` or `api_error` for easier debugging if needed
 
`btp/table_btp_datacenter`
  - The name of the file should be `table_btp_datacenter.go`
  - The function name should be `tableBTPDatacenter`
  - The name of the table should be `btp_datacenter`
  - The column descriptions should end with a `.`
  - The `geo_access` column does not have a description we should add it
  - It is better to use `d.EqualsQualString["region"]` instead of `equalQuals["region"].GetStringValue()`
 
`btp/table_btp_directory`
  - The name of the file should be `table_btp_directory.go`
  - The function name should be `tableBTPDirectory`
  - The name of the table should be `btp_directory`
  - The column descriptions should end with a `.`
  - The `directory_type` and `parent_guid1` columns do not have a description we should add it
  - It is better to use `d.EqualsQualString["region"]` instead of `equalQuals["region"].GetStringValue()`
 
`btp/table_btp_global_account`
  - The name of the file should be `table_btp_global_account.go`
  - The name of the table should be `btp_global_account`
  - The name of the list call should be `listGlobalAccounts`
  - The column descriptions should end with a `.`

`btp/table_btp_subaccount`
  - The name of the file should be `table_btp_subaccount.go`
  - The name of the table should be `btp_subaccount`
  - The name of the list call should be `listSubaccounts`
  - The column descriptions should end with a `.`
  - The `parent_type` column does not have a description we should add it
 
`btp/plugin.go`
  - The list of tables should be sorted in ascending order
 
`btp/utils.go`
  - Please rename the `btp.go` file to `utils.go`

`bt/types.go`
  - Rename to `types.go`

`README.md`
  - Please update the file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md) 
  - Please include all the necessary sections as mentioned above

`CHANGELOG.md`

  - Please draft an initial Changelog for the plugin release, an example would be as follows:
```
## v0.0.1 [TBD]

_What's new?_

- New tables added
  - [btp_datacenter](https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/main/btp/table_btp_datacenter.go)
  - [btp_directory](https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/main/btp/table_btp_directory.go)
  - [btp_global_account](https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/main/btp/table_btp_global_account.go)
  - [btp_subaccount](https://github.com/ajmaradiaga/steampipe-plugin-btp/blob/main/btp/table_btp_subaccount.go)
```
Please note that the example contains the name in singular assuming that the changelog will be added after updating the table names.

`Makefile`

  - The path is incorrect please update it to 
```
go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/ajmaradiaga/btp@latest/teampipe-plugin-btp.plugin *.go
```

`Follow-up questions`

- A couple of follow-up questions:
    - How are we handling the resource not found errors?
    - Do the APIs support pagination? I did not find any reference to it, but I want to make sure that we have checked that box before releasing it.
    - While working with the APIs did you encounter rate limit errors?
    - Please refer to https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information

Please let us know if you have questions, happy to help 👍

**Comment by ajmaradiaga** [comment]
Thanks for all the suggestion. Great timing as I'm currently working on the plugin and I will dedicate some time to make it "hub-ready"

**Comment by ajmaradiaga** [comment]
@madhushreeray30, I've made some progress on the suggestions that you've specified in this issue. The changes are in a separate branch... you can have a quick look here - https://github.com/ajmaradiaga/steampipe-plugin-btp/tree/plugin-feedback

**Comment by ajmaradiaga** [comment]
@madhushreeray30 everything is now ready for a review
